:toc: left

= Masterly

== 1. Introducción

Este trabajo está elaborado por los alumnos de segundo año de DAW del instituto Nicolau Copèrnic Xavi Carné y Oscar Alonso. 

Nuestra aplicación se llama "Masterly" será elaborada en lo que queda del curso de DAW2T. El propósito central de nuestro proyecto es la creación de una página web que sirva para comprar productos artesanales.

Para una buena navegación por la página web, se intentará crear un diseño cómodo, agradable y fácil de entender para todos usuarios que se conecten mediante una pantalla de ordenador convencional o un dispositivo móvil.


== 2. Seguimiento semanal

=== Semana 1

A lo largo de la primera semana, nos hemos encargado de realizar las tareas introductiorias del proyecto como son las siguientes:

* Creación del repositorio Gitlab y Kanban Trello (Samuel, Oscar y Xavi - 4h)
* Realización de la primera versión de la guia de estilos (Samuel, Oscar y Xavi - 6h)
* Diseño de la base de datos a partir de las tablas de "product" y "category" (Oscar y Xavi - 2h)
* Realización de scketchings, wireframe y mockups de la pantalla "home" en vista ordenador y mobil (Samuel y Oscar - 6h)

=== Semana 2

La segunda semana del proyecto es en la que hemos empezado a desarrollar la aplicación en Laravel. Las tareas más importantes de las que nos hemos encargado son las siguientes:

* Realización de scketchings, wireframe y mockups de la pantalla "home" en vista ordenador y mobil (Oscar y Xavi - 6h)
* Realizar los "seeders", "migrations" y "factories" de los modelos "Product" y "Category" (Xavi - 2h)
* Mostrar todos los datos de los productos en la página "home" (Xavi - 3h)
* Realización de la vista de la pantalla de producto (Oscar - 4h)

=== Semana 3

En la tercera semana, sobretodo hemos continuado implementando las funcionalidades de las pantallas de "home" y producto.

* Paginación del total de productos en la página home (Xavi - 3h)
* Filtración de productos a partir del nombre en una barra de búsqueda(Xavi - 4h)
* La página web redirige a la página de producto cuando se clica a un producto y se muestran los datos pertinentes (Oscar - 2h)
* Realización del logger (Samuel - 2h)
* Adición y eliminación de la id de los productos en el local storage y mostrarlos en el contador (Oscar - 4h)

=== Semana 4

La cuarta semana ha sido dedicada a terminar las funcionalidades de home y carrito. A la vez, se ha empezado la realización de las pantallas de login y registro.

* Realización de la vista de la pantalla de carrito (Oscar - 6h)
* Mostrar productos añadidos al carrito en la pantalla del carrito (Oscar - 8h)
* Refactorización del código storage listener y product fetcher (Oscar - 2h)
* Implementación categorias y subcategorias (Xavi - 12h)
* Adición de imágenes reales de la API unsplash (Xavi - 2h)
* Continuación de la implementación del logger (Samuel - 4h)
* Realización de la vista y la funcionalidad del login y registro (Samuel - 7h)

=== Semana 5

Esta semana, al haber dispuesto de únicamente 2 días de trabajo, no ha sido posible realizar tantos avances como en otras semanas. Aún así, hemos podido finalizar tareas pendientes de semanas anteriores.

* Obtención de productos y categorias reales y relación entre estos (Xavi | 5h previstas &Rightarrow; 6h reales)
* Eliminación productos del carrito del html, modificación precio total y cantidad de productos (Oscar | 4h previstas &Rightarrow; 6h reales)
* Cambio color icono carrito al añadir/eliminar producto al carrito desde home (Oscar | 1h prevista &Rightarrow; 1h real)
* Enviación email de verificación (Samuel | 3h previstas &Rightarrow; 5h reales)
* Implementación medidas rem (Oscar y Xavi | 1h prevista &Rightarrow; 1h real)

=== Semana 6

* Relación productos aleatorios y tags (Xavi | 5h previstas &Rightarrow; 4h reales)
* Implementación de la relación entre tiendas y productos (Xavi | 9h previstas &Rightarrow; 9h reales)
* Almacenamiento productos del carrito en la base de datos (Oscar | 10h previstas &Rightarrow; 12h reales)
* Productos añadidos al carrito desde la pantalla de producto (Oscar | 3h previstas &Rightarrow; 4h reales)

== 3. Diseño de Base de Datos

== 4. Guia de estilos

== 5. Diseño de pantallas

=== 5.1 Sketchings

=== 5.2 Wireframes

=== 5.3 Mockups

== 6. Manual de instalación/distribución

Dispones de dos maneras con las que poder utilizar la aplicación, mediante tu máquina local o mediante la utilización de entornos Vagrant.

== 7. Manual de usuario

== 8. Conclusiones

== 9. Líneas futuras

feedback al usuario, diseño con js

== 10. Glosario
